import io
import os
from typing import Optional
from docx import Document as DocxDocument
from docx.shared import Inches, Pt, RGBColor
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle

from backend.app.models.draft import Draft


class ExportService:
    def export_to_docx(self, draft: Draft) -> bytes:
        doc = DocxDocument()

        title_para = doc.add_paragraph()
        title_run = title_para.add_run(draft.title)
        title_run.font.size = Pt(22)
        title_run.font.bold = True
        title_para.paragraph_format.space_after = Pt(18)

        meta_para = doc.add_paragraph()
        meta_run = meta_para.add_run("Generated by SciLens — Automated Research Gap Identification System")
        meta_run.font.italic = True
        meta_run.font.color.rgb = RGBColor(100, 100, 100)
        meta_para.paragraph_format.space_after = Pt(24)

        for sec in draft.sections:
            heading = doc.add_heading(sec.section_name, level=1)
            heading.paragraph_format.space_before = Pt(14)
            heading.paragraph_format.space_after = Pt(6)

            body_para = doc.add_paragraph(sec.content)
            body_para.paragraph_format.line_spacing = 1.15
            body_para.paragraph_format.space_after = Pt(10)

        buffer = io.BytesIO()
        doc.save(buffer)
        buffer.seek(0)
        return buffer.getvalue()

    def export_to_pdf(self, draft: Draft) -> bytes:
        buffer = io.BytesIO()
        pdf_doc = SimpleDocTemplate(
            buffer,
            pagesize=letter,
            rightMargin=54,
            leftMargin=54,
            topMargin=54,
            bottomMargin=54,
        )

        styles = getSampleStyleSheet()
        title_style = ParagraphStyle(
            "DocTitle",
            parent=styles["Title"],
            fontSize=18,
            leading=22,
            textColor=colors.HexColor("#1A202C"),
            spaceAfter=14,
        )
        h1_style = ParagraphStyle(
            "DocH1",
            parent=styles["Heading1"],
            fontSize=13,
            leading=16,
            textColor=colors.HexColor("#2B6CB0"),
            spaceBefore=12,
            spaceAfter=6,
        )
        body_style = ParagraphStyle(
            "DocBody",
            parent=styles["Normal"],
            fontSize=10,
            leading=14,
            textColor=colors.HexColor("#2D3748"),
            spaceAfter=8,
        )

        story = []
        clean_title = draft.title.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
        story.append(Paragraph(clean_title, title_style))
        story.append(Paragraph("<i>SciLens Research Proposal &amp; Literature Review</i>", body_style))
        story.append(Spacer(1, 16))

        for sec in draft.sections:
            sec_name = sec.section_name.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
            story.append(Paragraph(sec_name, h1_style))

            content_text = sec.content.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace("\n", "<br/>")
            story.append(Paragraph(content_text, body_style))
            story.append(Spacer(1, 8))

        pdf_doc.build(story)
        buffer.seek(0)
        return buffer.getvalue()

    def export_to_markdown(self, draft: Draft) -> bytes:
        """Export draft to a clean, readable Markdown string in UTF-8 bytes."""
        lines = [
            f"# {draft.title}",
            "",
            "> *Generated by SciLens — Automated Research Gap Identification System*",
            "",
            "---",
            "",
        ]

        for sec in draft.sections:
            lines.append(f"## {sec.section_name}")
            lines.append("")
            lines.append(sec.content)
            lines.append("")

        md_content = "\n".join(lines)
        return md_content.encode("utf-8")

    def export_literature_review_to_docx(self, lit_review: dict, topic: str = "Research Topic") -> bytes:
        """Exports a LiteratureReviewResponse dictionary to DOCX."""
        doc = DocxDocument()

        title_para = doc.add_paragraph()
        title_run = title_para.add_run(f"Systematic Literature Review: {topic}")
        title_run.font.size = Pt(22)
        title_run.font.bold = True
        title_para.paragraph_format.space_after = Pt(14)

        meta_para = doc.add_paragraph()
        meta_run = meta_para.add_run(
            f"Organization: {lit_review.get('organization', 'Thematic')} • "
            f"Citation Style: {lit_review.get('citation_style', 'APA 7')} • "
            f"Depth: {lit_review.get('review_depth', 'Detailed')}"
        )
        meta_run.font.italic = True
        meta_run.font.color.rgb = RGBColor(100, 100, 100)
        meta_para.paragraph_format.space_after = Pt(20)

        for sec in lit_review.get("sections", []):
            title = sec.get("title", "Section")
            heading = doc.add_heading(title, level=1)
            heading.paragraph_format.space_before = Pt(14)
            heading.paragraph_format.space_after = Pt(6)

            body_para = doc.add_paragraph(sec.get("content", ""))
            body_para.paragraph_format.line_spacing = 1.15
            body_para.paragraph_format.space_after = Pt(10)

        for table_data in lit_review.get("tables", []):
            t_title = table_data.get("title", "Comparative Matrix")
            t_head = doc.add_heading(t_title, level=2)
            t_head.paragraph_format.space_before = Pt(14)
            t_head.paragraph_format.space_after = Pt(6)

            headers = table_data.get("headers", [])
            rows = table_data.get("rows", [])
            if headers:
                t = doc.add_table(rows=len(rows) + 1, cols=len(headers))
                t.style = 'Table Grid'
                for c_idx, h in enumerate(headers):
                    cell = t.cell(0, c_idx)
                    cell.text = str(h)
                    for paragraph in cell.paragraphs:
                        for run in paragraph.runs:
                            run.font.bold = True
                for r_idx, row in enumerate(rows):
                    for c_idx, val in enumerate(row):
                        if c_idx < len(headers):
                            t.cell(r_idx + 1, c_idx).text = str(val)

        buffer = io.BytesIO()
        doc.save(buffer)
        buffer.seek(0)
        return buffer.getvalue()

    def export_literature_review_to_pdf(self, lit_review: dict, topic: str = "Research Topic") -> bytes:
        """Exports a LiteratureReviewResponse dictionary to PDF."""
        buffer = io.BytesIO()
        pdf_doc = SimpleDocTemplate(
            buffer,
            pagesize=letter,
            rightMargin=54,
            leftMargin=54,
            topMargin=54,
            bottomMargin=54,
        )

        styles = getSampleStyleSheet()
        title_style = ParagraphStyle(
            "DocTitle",
            parent=styles["Title"],
            fontSize=18,
            leading=22,
            textColor=colors.HexColor("#1A202C"),
            spaceAfter=14,
        )
        h1_style = ParagraphStyle(
            "DocH1",
            parent=styles["Heading1"],
            fontSize=13,
            leading=16,
            textColor=colors.HexColor("#2B6CB0"),
            spaceBefore=12,
            spaceAfter=6,
        )
        body_style = ParagraphStyle(
            "DocBody",
            parent=styles["Normal"],
            fontSize=10,
            leading=14,
            textColor=colors.HexColor("#2D3748"),
            spaceAfter=8,
        )

        story = []
        clean_title = f"Systematic Literature Review: {topic}".replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
        story.append(Paragraph(clean_title, title_style))
        story.append(Paragraph(f"<i>SciLens Grounded Literature Review • Style: {lit_review.get('citation_style', 'APA 7')}</i>", body_style))
        story.append(Spacer(1, 14))

        for sec in lit_review.get("sections", []):
            s_name = sec.get("title", "Section").replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
            story.append(Paragraph(s_name, h1_style))
            content = sec.get("content", "").replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace("\n", "<br/>")
            story.append(Paragraph(content, body_style))
            story.append(Spacer(1, 8))

        pdf_doc.build(story)
        buffer.seek(0)
        return buffer.getvalue()

    def export_literature_review_to_markdown(self, lit_review: dict, topic: str = "Research Topic") -> bytes:
        """Exports a LiteratureReviewResponse dictionary to Markdown."""
        lines = [
            f"# Systematic Literature Review: {topic}",
            "",
            f"> *Organization: {lit_review.get('organization', 'Thematic')} • Citation Style: {lit_review.get('citation_style', 'APA 7')} • Depth: {lit_review.get('review_depth', 'Detailed')}*",
            "",
            "---",
            "",
        ]

        for sec in lit_review.get("sections", []):
            lines.append(f"## {sec.get('title', 'Section')}")
            lines.append("")
            lines.append(sec.get("content", ""))
            lines.append("")

        for table_data in lit_review.get("tables", []):
            t_title = table_data.get("title", "Comparative Matrix")
            lines.append(f"### {t_title}")
            lines.append("")
            headers = table_data.get("headers", [])
            rows = table_data.get("rows", [])
            if headers:
                lines.append("| " + " | ".join(headers) + " |")
                lines.append("| " + " | ".join(["---"] * len(headers)) + " |")
                for r in rows:
                    lines.append("| " + " | ".join(str(c) for c in r) + " |")
            lines.append("")

        return "\n".join(lines).encode("utf-8")

